version: '3.9'

services:
  traefik:
    image: traefik:latest
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yml:/traefik.yml:ro
      - ./config/config.yml:/config.yml:ro
      - ./logs:/var/log/traefik
      - ./letsencrypt:/letsencrypt
    environment:
      - DUCKDNS_TOKEN=91c740a0-c347-4812-a00b-33e6be6e840f
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=http
      - traefik.http.routers.taefik.rule=Host(`traefik.tinkerbells.duckdns.org`)
      - traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.routers.traefik.middlewares=traefik-https-redirect
      - traefik.http.routers.traefik-secure.entrypoints=https
      - traefik.http.routers.traefik-secure.rule=Host(`traefik.tinkerbells.duckdns.org`)
      - traefik.http.routers.traefik-secure.service=api@internal
  whoami:
    image: traefik/whoami:v1.8
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.entrypoints=http"
      - "traefik.http.routers.whoami.rule=Host(`whoami.tinkerbells.duckdns.org`)"
      - "traefik.http.middlewares.whoami-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.whoami.middlewares=whoami-https-redirect"
      - "traefik.http.routers.whoami-secure.entrypoints=https"
      - "traefik.http.routers.whoami-secure.rule=Host(`whoami.tinkerbells.duckdns.org`)"
      - "traefik.http.routers.whoami-secure.service=whoami"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
      - "traefik.http.routers.whoami-secure.middlewares=middlewares-authentik@file"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    name: proxy

volumes:
  letsencrypt:
    name: letsencrypt


