api:
  dashboard: true
  debug: true
entryPoints:
  http:
    address: ":80"
    http:
      middlewares:
        - crowdsec-bouncer@file
      redirections:
        entryPoint:
           to: https
           scheme: https


  https:
    address: ":443"
    http:
      middlewares:
        - crowdsec-bouncer@file
      tls:
        certResolver: myresolver
        domains:
          - main: tinkerbells.duckdns.org
          - sans: '*.tinkerbells.duckdns.org'




serversTransport:
   insecureSkipVerify: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /config.yml
    watch: true

certificatesResolvers:
  myresolver:
    acme:
      email: untermenschH@protonmail.com 
      storage: /letsencrypt/acme.json
      dnsChallenge:
        provider: duckdns        
        delayBeforeCheck: 120
log:
  level: "DEBUG"
  filePath: "/var/log/traefik/traefik.log"

accessLog:
  filePath: "/var/log/traefik/access.log"
